theme: jekyll-theme-cayman
title: [Detecting Fraudulent Credit Card Transactions]
description: [Building a robust fraud detector on an imbalanced dataset using Gradient Boosting models and Artificial Neural Networks] 
